print("Tabuada do 6")

print("5 * 1 =" , 5 * 1)
print("5 * 2 = " , 5 * 2)
print("5 * 3 = " , 5 * 3)
print("5 * 4 = " , 5 * 4)
print("5 * 5 = " , 5 * 5)
print("5 * 6 = " , 5 * 6)
print("5 * 7 = " , 5 * 7)
print("5 * 8 = " , 5 * 8)
print("5 * 9 = " , 5 * 9)
print("5 * 10 = " , 5 * 10)

numero = 7
print("Tabuada do " , numero)

print(numero, "* 1 = ", numero *1)
print(numero, "* 2 = ", numero *2)
print(numero, "* 3 = ", numero *3)
print(numero, "* 4 = ", numero *4)
print(numero, "* 5 = ", numero *5)
print(numero, "* 6 = ", numero *6)
print(numero, "* 7 = ", numero *7)
print(numero, "* 8 = ", numero *8)
print(numero, "* 9 = ", numero *9)
print(numero, "* 10 = ", numero *10)